### ISSUE TITLE
Dependency on jQuery just for $.ajax

### ISSUE THREAD

**Issue by Ezku** [oauth-io/oauth-phonegap#13]
Hi guys,

I recently had to work around an issue related to this plugin's dependency on jQuery. You're only using the $.ajax portion of it in OAuth.http, so you're mandating that your users take on a pretty heavy dependency for something pretty minimal and non-integral to your use case. Fortunately, this is easily redeemed.

I used [xhr-ajax](https://github.com/craig0990/xhr-ajax) to implement my workaround, and it appears to work perfectly. I'd submit a pull request, but I don't have any idea about your preferred means of bundling dependencies. Hope you can manage to find a solution yourself, but let me know if I can be of assistance.

Cheers,
Eevert

**Comment by bumpmann** [comment]
jquery is included with a lightweighted compilation to include $ ajax in a closure so it's now light and won't pollute the other code.
