### ISSUE TITLE
Insertion of jQuery without my knowledge

### ISSUE THREAD

**Issue by ptbrowne** [oauth-io/oauth-phonegap#25]
Hello,

When OAuth does not find jQuery, it tries to be clever and inserts jQuery. The problem is that I use Zepto so I would prefer if it would check for $, fails if it does not find window.$ and fails hard instead of doing the magic of inserting a script tag with code.jquery.com/jquery-2.11.1.js . Moreover, since it is on mobile, we cannot rely on the network being there when the user opens the application.

What do you think ?

**Comment by bumpmann** [comment]
jquery is included with a lightweighted compilation to include $ ajax in a closure so it's now light and won't pollute the other code.
