### ISSUE TITLE
Could not connect to the server.

### ISSUE THREAD

**Issue by neocite** [oauth-io/oauth-phonegap#29]
Hello. I try to use this oAuth lib but i have a problem:

"webView:didFailLoadWithError - -1004: Could not connect to the server."

Can i help me?

I'm using in the same project oAuth plugin and the Facebook plugin (oficial plugin).

**Comment by rakeshpalivela** [comment]
Hi ,

I am also getting same problem. After successfully logged into facebook/twitter I am getting this error webView:didFailLoadWithError - -1004: Could not connect to the server.

In config.xml I provide <access origin="*" />
