### ISSUE TITLE
"The popup was closed" error message

### ISSUE THREAD

**Issue by iruffner** [oauth-io/oauth-phonegap#33]
I updated to 0.2.4, which also updated the InAppBrowser to 0.5.1. Now, when I use the popup login, I get the result object, but I am also getting the error string back that says "The popup was closed". The login seems successful, so I'm not sure why I'm receiving the error message. Any guidance on why that might be?

Edit: Sorry forgot to say that this is running on iOS 7.1.2.

**Comment by bumpmann** [comment]
The issue should be resolved with the latest version, there are more checks about it since the old versions
