### ISSUE TITLE
result object

### ISSUE THREAD

**Issue by jjshoe** [oauth-io/oauth-phonegap#41]
Is there some reason we can't call Oauth.result or OAuth.getResult to get the last result object?

**Comment by angelxmoreno** [comment]
`Oauth.result ` to get the last result would not make a lot of sense when you have a user logged in with multiple social accounts. However, `var twitterResult = OAuth.create('twitter');` or `var facebookResult = OAuth.create('facebook');` can give you a result object specific to the social login.

**Comment by bumpmann** [comment]
Thanks for the reply.

`OAuth.create` uses the local storage to store and fetch cached tokens so you still have to use `OAuth.popup` to cache the tokens from the providers, depending on their expiry.
