### ISSUE TITLE
OAauth is undefined the first time around

### ISSUE THREAD

**Issue by jjshoe** [oauth-io/oauth-phonegap#42]
Ionic, cordova, and an android device. 

1) Grab https://github.com/jjshoe/Meetendance
2) Run
3) Login
4) Close app
5) Re-launch app
6) Notice you'll get: "OAuth not found" alert
7) Click on the "Help" tab
8) Click on the "Events" tab
9) Notice you'll get: "good"

Thoughts on what's going on that oauth is only defined so late in the game?

**Comment by angelxmoreno** [comment]
Please close this @jjshoe
