### ISSUE TITLE
Missing required parameter: scope

### ISSUE THREAD

**Issue by hobzcalvin** [oauth-io/oauth-phonegap#54]
When I try using OAuth.popup('google') I get the attached screenshot:
```
Error: invalid_request
Missing required parameter: scope
Request Details
response_type=code
redirect_uri=https://oauth.io/auth
state=athxRYu1cR1BrFIxtJmSP8GifWA
```

Is this project being actively maintained? I see someone reported a similar issue on the php client:
https://github.com/oauth-io/sdk-php/issues/19

![ios simulator screen shot jun 8 2015 6 49 31 pm](https://cloud.githubusercontent.com/assets/82265/8049104/206e68b4-0e0f-11e5-9dfa-a1aa56d83387.png)

**Comment by thyb** [comment]
Are you sure you have correctly setup the `scope` in the OAuth.io dashboard?

I'm able to authorize on Google/Google+ if the `scope` is set. I reproduce your issue only if I let the `scope` field blank.

**Comment by hobzcalvin** [comment]
That's probably it.

**Comment by pathikvejani** [comment]
@thyb Where to set up the `scope` param? Can you please guide? I am using php and trying to login with google plus.
