### ISSUE TITLE
Update latest OAuth.io SDK

### ISSUE THREAD

**Issue by angelxmoreno** [oauth-io/oauth-phonegap#65]
Are there any plans to introduce the newer version of OAuth.io ? The current version in this plugin is missing the `User` module.

**Comment by thyb** [comment]
We're working on it, it should be ready next week.
This update should close most of current open issue.

**Comment by angelxmoreno** [comment]
amazing! ty.

**Comment by bumpmann** [comment]
0.5.0 released !
